package com.wings.database;

import com.wings.models.Bird;
import com.wings.repository.BirdRepository;

import java.sql.SQLException;
import java.util.UUID;

public class BirdDataLoader {
    public static void loadBirds(BirdRepository birdRepo) throws SQLException {
        String[][] birdData = {
            {"Snow Goose", "Wetlands", "0.1"},
            {"Canada Goose", "Wetlands", "0.3"},
            {"Wood Duck", "Wetlands", "0.1"},
            {"Gadwall", "Wetlands", "0.1"},
            {"American Wigeon", "Wetlands", "0.1"},
            {"Mallard", "Wetlands", "0.9"},
            {"Blue-winged Teal", "Wetlands", "0.2"},
            {"Northern Shoveler", "Wetlands", "0.2"},
            {"Northern Pintail", "Wetlands", "0.1"},
            {"Green-winged Teal", "Wetlands", "0.2"},
            {"Ring-necked Duck", "Wetlands", "0.1"},
            {"Lesser Scaup", "Wetlands", "0.2"},
            {"Hooded Merganser", "Wetlands", "0.1"},
            {"Ruddy Duck", "Wetlands", "0.1"},
            {"Pied-billed Grebe", "Wetlands", "0.1"},
            {"Double-crested Cormorant", "Wetlands", "0.7"},
            {"Neotropic Cormorant", "Wetlands", "0.1"},
            {"American White Pelican", "Wetlands", "0.1"},
            {"American Bittern", "Wetlands", "0.1"},
            {"Great Blue Heron", "Wetlands", "0.6"},
            {"Great Egret", "Wetlands", "0.6"},
            {"Snowy Egret", "Wetlands", "0.4"},
            {"Little Blue Heron", "Wetlands", "0.4"},
            {"Cattle Egret", "Fields", "0.2"},
            {"Green Heron", "Wetlands", "0.5"},
            {"Black-crowned Night-Heron", "Wetlands", "0.1"},
            {"Yellow-crowned Night-Heron", "Wetlands", "0.1"},
            {"Black Vulture", "Open Areas", "0.4"},
            {"Turkey Vulture", "Open Areas", "0.6"},
            {"Osprey", "Wetlands", "0.1"},
            {"Mississippi Kite", "Open Areas", "0.2"},
            {"Northern Harrier", "Open Areas", "0.1"},
            {"Sharp-shinned Hawk", "Forests", "0.4"},
            {"Cooper's Hawk", "Forests", "0.6"},
            {"Red-shouldered Hawk", "Forests", "0.5"},
            {"Broad-winged Hawk", "Forests", "0.2"},
            {"Swainson's Hawk", "Open Areas", "0.4"},
            {"Red-tailed Hawk", "Open Areas", "0.9"},
            {"American Kestrel", "Open Areas", "0.5"},
            {"Peregrine Falcon", "Urban", "0.1"},
            {"Merlin", "Open Areas", "0.1"},
            {"Sora", "Wetlands", "0.1"},
            {"American Coot", "Wetlands", "0.5"},
            {"Killdeer", "Fields", "0.7"},
            {"Spotted Sandpiper", "Wetlands", "0.1"},
            {"Solitary Sandpiper", "Wetlands", "0.1"},
            {"Willet", "Wetlands", "0.1"},
            {"Lesser Yellowlegs", "Wetlands", "0.1"},
            {"Long-billed Dowitcher", "Wetlands", "0.1"},
            {"Upland Sandpiper", "Fields", "0.4"},
            {"Wilson's Snipe", "Wetlands", "0.4"},
            {"American Woodcock", "Forests", "0.1"},
            {"Wilson's Phalarope", "Wetlands", "0.1"},
            {"Bonaparte's Gull", "Wetlands", "0.1"},
            {"Franklin's Gull", "Wetlands", "0.3"},
            {"Ring-billed Gull", "Wetlands", "0.7"},
            {"Forster's Tern", "Wetlands", "0.1"},
            {"Rock Pigeon", "Urban", "0.9"},
            {"Eurasian Collared-Dove", "Urban", "0.4"},
            {"White-winged Dove", "Urban", "0.9"},
            {"Mourning Dove", "Urban", "0.9"},
            {"Inca Dove", "Urban", "0.4"},
            {"Yellow-billed Cuckoo", "Forests", "0.7"},
            {"Black-billed Cuckoo", "Forests", "0.1"},
            {"Eastern Screech-Owl", "Forests", "0.1"},
            {"Great Horned Owl", "Forests", "0.1"},
            {"Barred Owl", "Forests", "0.3"},
            {"Common Nighthawk", "Urban", "0.4"},
            {"Chuck-will's-widow", "Forests", "0.1"},
            {"Chimney Swift", "Urban", "0.7"},
            {"Ruby-throated Hummingbird", "Gardens", "0.4"},
            {"Black-chinned Hummingbird", "Gardens", "0.4"},
            {"Rufous Hummingbird", "Gardens", "0.1"},
            {"Belted Kingfisher", "Wetlands", "0.3"},
            {"Red-bellied Woodpecker", "Forests", "0.9"},
            {"Red-headed Woodpecker", "Forests", "0.1"},
            {"Yellow-bellied Sapsucker", "Forests", "0.7"},
            {"Downy Woodpecker", "Forests", "0.9"},
            {"Hairy Woodpecker", "Forests", "0.7"},
            {"Northern Flicker", "Forests", "0.7"},
            {"Olive-sided Flycatcher", "Forests", "0.2"},
            {"Eastern Wood-Pewee", "Forests", "0.4"},
            {"Yellow-bellied Flycatcher", "Forests", "0.2"},
            {"Alder Flycatcher", "Forests", "0.4"},
            {"Willow Flycatcher", "Forests", "0.4"},
            {"Least Flycatcher", "Forests", "0.5"},
            {"Eastern Phoebe", "Urban", "0.7"},
            {"Great Crested Flycatcher", "Forests", "0.7"},
            {"Western Kingbird", "Open Areas", "0.7"},
            {"Eastern Kingbird", "Open Areas", "0.7"},
            {"Scissor-tailed Flycatcher", "Open Areas", "0.7"},
            {"Loggerhead Shrike", "Open Areas", "0.3"},
            {"White-eyed Vireo", "Forests", "0.7"},
            {"Bell's Vireo", "Forests", "0.1"},
            {"Yellow-throated Vireo", "Forests", "0.2"},
            {"Blue-headed Vireo", "Forests", "0.4"},
            {"Warbling Vireo", "Forests", "0.4"},
            {"Philadelphia Vireo", "Forests", "0.1"},
            {"Red-eyed Vireo", "Forests", "0.7"},
            {"Blue Jay", "Forests", "0.9"},
            {"American Crow", "Urban", "0.9"},
            {"Purple Martin", "Urban", "0.6"},
            {"Northern Rough-winged Swallow", "Urban", "0.2"},
            {"Bank Swallow", "Urban", "0.4"},
            {"Cliff Swallow", "Urban", "0.2"},
            {"Barn Swallow", "Urban", "0.7"},
            {"Carolina Chickadee", "Forests", "0.9"},
            {"Tufted Titmouse", "Forests", "0.9"},
            {"Red-breasted Nuthatch", "Forests", "0.1"},
            {"White-breasted Nuthatch", "Forests", "0.5"},
            {"Brown Creeper", "Forests", "0.4"},
            {"Carolina Wren", "Forests", "0.9"},
            {"Bewick's Wren", "Forests", "0.2"},
            {"House Wren", "Urban", "0.4"},
            {"Winter Wren", "Forests", "0.6"},
            {"Sedge Wren", "Wetlands", "0.1"},
            {"Marsh Wren", "Wetlands", "0.1"},
            {"Golden-crowned Kinglet", "Forests", "0.5"},
            {"Ruby-crowned Kinglet", "Forests", "0.7"},
            {"Blue-gray Gnatcatcher", "Forests", "0.5"},
            {"Eastern Bluebird", "Fields", "0.7"},
            {"Veery", "Forests", "0.1"},
            {"Gray-cheeked Thrush", "Forests", "0.1"},
            {"Swainson's Thrush", "Forests", "0.6"},
            {"Hermit Thrush", "Forests", "0.6"},
            {"Wood Thrush", "Forests", "0.4"},
            {"American Robin", "Urban", "0.7"},
            {"Gray Catbird", "Forests", "0.2"},
            {"Northern Mockingbird", "Urban", "0.9"},
            {"Brown Thrasher", "Forests", "0.4"},
            {"European Starling", "Urban", "0.9"},
            {"American Pipit", "Open Areas", "0.4"},
            {"Cedar Waxwing", "Forests", "0.5"},
            {"Tennessee Warbler", "Forests", "0.4"},
            {"Orange-crowned Warbler", "Forests", "0.4"},
            {"Blue-winged Warbler", "Forests", "0.1"},
            {"Worm-eating Warbler", "Forests", "0.1"},
            {"Nashville Warbler", "Forests", "0.7"},
            {"Northern Parula", "Forests", "0.2"},
            {"Yellow Warbler", "Forests", "0.4"},
            {"Chestnut-sided Warbler", "Forests", "0.4"},
            {"Magnolia Warbler", "Forests", "0.4"},
            {"Yellow-rumped Warbler", "Forests", "0.7"},
            {"Black-throated Green Warbler", "Forests", "0.4"},
            {"Blackburnian Warbler", "Forests", "0.2"},
            {"Pine Warbler", "Forests", "0.4"},
            {"Yellow-Throated Warbler", "Forests", "0.1"},
            {"Bay-breasted Warbler", "Forests", "0.2"},
            {"Blackpoll Warbler", "Forests", "0.1"},
            {"Black-and-white Warbler", "Forests", "0.4"},
            {"American Redstart", "Forests", "0.2"},
            {"Ovenbird", "Forests", "0.2"},
            {"Northern Waterthrush", "Wetlands", "0.2"},
            {"Louisiana Waterthrush", "Wetlands", "0.2"},
            {"Mourning Warbler", "Forests", "0.4"},
            {"Prothonotary Warbler", "Wetlands", "0.1"},
            {"Common Yellowthroat", "Forests", "0.4"},
            {"Wilson's Warbler", "Forests", "0.5"},
            {"Canada Warbler", "Forests", "0.2"},
            {"Yellow-breasted Chat", "Forests", "0.2"},
            {"Summer Tanager", "Forests", "0.2"},
            {"Scarlet Tanager", "Forests", "0.1"},
            {"Spotted Towhee", "Forests", "0.3"},
            {"Eastern Towhee", "Forests", "0.3"},
            {"Chipping Sparrow", "Fields", "0.6"},
            {"Clay-colored Sparrow", "Fields", "0.2"},
            {"Field Sparrow", "Fields", "0.4"},
            {"Vesper Sparrow", "Fields", "0.2"},
            {"Lark Sparrow", "Fields", "0.2"},
            {"Savannah Sparrow", "Fields", "0.5"},
            {"Grasshopper Sparrow", "Fields", "0.2"},
            {"Le Conte's Sparrow", "Fields", "0.1"},
            {"Fox Sparrow", "Fields", "0.2"},
            {"Song Sparrow", "Fields", "0.6"},
            {"Lincoln's Sparrow", "Fields", "0.5"},
            {"Swamp Sparrow", "Fields", "0.4"},
            {"White-throated Sparrow", "Fields", "0.7"},
            {"Harris's Sparrow", "Fields", "0.1"},
            {"White-crowned Sparrow", "Fields", "0.1"},
            {"Dark-eyed Junco", "Fields", "0.6"},
            {"Northern Cardinal", "Forests", "0.9"},
            {"Rose-breasted Grosbeak", "Forests", "0.4"},
            {"Blue Grosbeak", "Fields", "0.4"},
            {"Lazuli Bunting", "Fields", "0.1"},
            {"Indigo Bunting", "Fields", "0.6"},
            {"Painted Bunting", "Fields", "0.2"},
            {"Dickcissel", "Fields", "0.4"},
            {"Red-winged Blackbird", "Wetlands", "0.5"},
            {"Eastern Meadowlark", "Fields", "0.2"},
            {"Western Meadowlark", "Fields", "0.2"},
            {"Rusty Blackbird", "Wetlands", "0.1"},
            {"Common Grackle", "Urban", "0.7"},
            {"Great-tailed Grackle", "Open Areas", "0.9"},
            {"Brown-headed Cowbird", "Urban", "0.6"},
            {"Orchard Oriole", "Forests", "0.4"},
            {"Baltimore Oriole", "Forests", "0.6"},
            {"Purple Finch", "Forests", "0.1"},
            {"House Finch", "Urban", "0.9"},
            {"Pine Siskin", "Forests", "0.4"},
            {"American Goldfinch", "Fields", "0.7"},
            {"House Sparrow", "Urban", "0.9"}
        };
        
        for (String[] data : birdData) {
            double rarity = 0.0;
            try {
                if (data[2] != null && !data[2].trim().isEmpty() && !data[2].equals("-")) {
                    rarity = Double.parseDouble(data[2]);
                }
            } catch (NumberFormatException e) {
                rarity = 0.0; 
            }
            Bird bird = new Bird(UUID.randomUUID(), data[0], data[1], rarity);
            birdRepo.saveBird(bird);
        }
        
        System.out.println("Loaded " + birdData.length + " birds into database");
    }
}